---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    sudo_hardening: True
  tasks:
    - name: Include role 'ansible-role-sudo'
      ansible.builtin.include_role:
        name: ansible-role-sudo
